### ISSUE TITLE
How to use multi-GPU to train the model?

### ISSUE THREAD

**Issue by fengwhu** [RQuispeC/pytorch-ACSCP#2]
Hi, I have tried to train the ACSCP model using single GPU by default, but it seemed too slow. Thus, I wonder how to use multi-GPU to train the model?

**Comment by RQuispeC** [comment]
hi @fengwhu , sorry for answering after so long. I have not tried using multi-GPU but this link may help you https://pytorch.org/tutorials/beginner/former_torchies/parallelism_tutorial.html

To make training faster you may want to increase `--train-batch` , I used 24 images per batch due to GPU capability (around 11 gb)

**Comment by fengwhu** [comment]
Thank you.
